---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-aee-default-env
data:
  ANSIBLE_CALLBACKS_ENABLED: "ansible.posix.profile_tasks,yaml"
  ANSIBLE_DISPLAY_ARGS_TO_STDOUT: "True"
  ANSIBLE_VERBOSITY: "1"
  ANSIBLE_FORCE_COLOR: "True"
  ANSIBLE_SSH_ARGS: "-C -o ControlMaster=auto -o ControlPersist=80s"
